CREATE ROLE ar_admin;

GRANT CREATE SESSION TO ar_admin;

GRANT CREATE TABLE TO ar_admin;
GRANT CREATE PROCEDURE TO ar_admin;
GRANT CREATE TRIGGER TO ar_admin;
GRANT CREATE VIEW TO ar_admin;
GRANT CREATE SEQUENCE TO ar_admin;

GRANT ALTER ANY TABLE TO ar_admin;
GRANT ALTER ANY PROCEDURE TO ar_admin;
GRANT ALTER ANY TRIGGER TO ar_admin;
GRANT ALTER ANY SEQUENCE TO ar_admin;

GRANT DROP ANY TABLE TO ar_admin;
GRANT DROP ANY PROCEDURE TO ar_admin;
GRANT DROP ANY TRIGGER TO ar_admin;
GRANT DROP ANY SEQUENCE TO ar_admin;
GRANT DROP ANY VIEW TO ar_admin;